apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lapis
  name: lapis-api
spec:
  template:
    spec:
      containers:
      - name: lapis-api
        image: repository.preclikos.cz:5000/lapis/api
