apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - deployment.yaml
  
images:
- name: repository.preclikos.cz:5000/lapis/api
  newName: repository.preclikos.cz:5000/lapis/api
  newTag: IMAGE_TAG
