name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  kustomize:
    runs-on: self-hosted
    steps:
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
             repository.preclikos.cz:5000/lapis/api
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Checkout
        uses: actions/checkout@v3
      - name: 'Kustomize Build'
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kustomize: '4.5.7'
      - run: |
          kustomize build k8s/overlays/$GITHUB_ENV
