name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  kustomize:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - name: 'Kustomize Build'
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: '4.5.7'
          kustomize_build_dir: './k8s/overlay/production'
          kustomize_output_file: "kustomize_deploy.yaml"
          kustomize_build_options: "--load_restrictor none"
