name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  deploy:
    runs-on: self-hosted
    needs: docker
    steps:
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
             repository.preclikos.cz:5000/lapis/api
          tags: |
            type=sha
      -
        name: Checkout
        uses: actions/checkout@v3
      - name: 'Kubernetes Tools'
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kustomize: '4.5.7'
          kubectl: '1.17.1'
      - name: 'Kustomize Build'
        run: |
          printenv
