name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  kustomize:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - name: 'Kustomize Build'
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kustomize: '4.5.7'
      - run: |
          kustomize version
