name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  kustomize:
    runs-on: self-hosted
    steps:
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
             repository.preclikos.cz:5000/lapis/api
          tags: |
            type=sha
      -
        name: Checkout
        uses: actions/checkout@v3
      - name: 'Kubernetes Tools'
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kustomize: '4.5.7'
      - name: 'Kustomize Build'
        run: |
          cd k8s/base
          kustomize edit set image repository.preclikos.cz:5000/lapis/api=repository.preclikos.cz:5000/lapis/api:${{ steps.meta.outputs.tags }}
          kustomize build ../../k8s/overlays/production
          mkdir .kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > .kube/config
          kubectl get pods
