name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Cleanup build folder'
      run: |
        ls -la ./
        rm -rf ./* || true
        rm -rf ./.??* || true
        ls -la ./
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -o publish
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
       name: dotnet-app
       path: publish

  deploy:
    permissions:
      contents: none
    runs-on: self-hosted
    needs: build
    environment:
      name: 'Production'
      
    steps:
    - name: 'Cleanup build folder'
      run: |
        ls -la ./
        rm -rf ./* || true
        rm -rf ./.??* || true
        ls -la ./
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: dotnet-app
    - name: SCP Files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        rm: true
        overwrite: true
        source: "."
        target: "/home/lapis-api/api"
    - name: List  
      run: ls
